# Generated by Django 2.2.7 on 2019-12-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrib_percent', models.IntegerField(help_text='Процент вклада сотрудника', null=True, verbose_name='Процент вклада')),
            ],
            options={
                'verbose_name': 'Процент вклада',
                'verbose_name_plural': 'Проценты вклада',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя сотрудника', max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(help_text='Введите фамилию сотрудника', max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(help_text='Введите отчество сотрудника', max_length=50, verbose_name='Отчество')),
                ('job_duty', models.CharField(help_text='Введите должность работника', max_length=50, verbose_name='Должность')),
                ('status_choices', models.CharField(choices=[('Работает', 'Работает'), ('Не работает', 'Не работает')], default='Работает', max_length=11, verbose_name='Статус сотрудника')),
                ('passport_series', models.CharField(help_text='Введите серию паспорта', max_length=4, null=True, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(help_text='Введите номер паспорта', max_length=6, null=True, verbose_name='Номер паспорта')),
                ('gave_out_by', models.TextField(help_text='Введите, кем выдан паспорт', max_length=200, null=True, verbose_name='Кем выдан')),
                ('gave_out_date', models.DateField(help_text='Введите, когда выдан паспорт', null=True, verbose_name='Когда выдан')),
                ('registred', models.TextField(help_text='Зарегистрирован', max_length=300, null=True, verbose_name='Зарегистрирован')),
            ],
            options={
                'verbose_name': 'Сотрудника',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Введите дату создания документа', null=True, verbose_name='Дата создания документа')),
                ('number', models.CharField(default='121219', help_text='Сгенерирован автоматически по маске (день, месяц, год, порядковый номер)', max_length=100, verbose_name='Номер документа')),
                ('name', models.CharField(help_text='Введите наименование документа', max_length=100, null=True, verbose_name='Наименование документа')),
                ('annotation', models.TextField(help_text='Введите текст аннотации', max_length=300, null=True, verbose_name='Аннотация')),
                ('language_choices', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Java Script', 'Java Script'), ('Go', 'Go'), ('C', 'C'), ('C++', 'C++')], default='Python', max_length=20, verbose_name='Язык программирования')),
                ('authors_of_RID', models.ManyToManyField(related_name='documents', through='acts_creator.Contribution', to='acts_creator.Employee', verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddField(
            model_name='contribution',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acts_creator.Documents', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acts_creator.Employee', verbose_name='Сотрудник'),
        ),
    ]
