# Generated by Django 2.2.7 on 2019-12-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acts_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acts_creator.Documents', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acts_creator.Employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='number',
            field=models.CharField(default='231219', help_text='Дополнить шаблон порядковым номером документа', max_length=100, verbose_name='Номер документа'),
        ),
    ]
